# Uncomment the next line to define a global platform for your project
platform :ios, '15.4'

target 'MarvelHeroesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelHeroesApp

  # The ultimate API for iOS & OS X Auto Layout — impressively simple, immensely powerful. Objective-C and Swift compatible.
  # https://github.com/PureLayout/PureLayout
  pod 'PureLayout', '3.1.9'

  # Kingfisher is a powerful, pure-Swift library for downloading and caching images from the web.
  # https://github.com/onevcat/Kingfisher
  pod 'Kingfisher', '7.2.0'

  # Network abstraction layer written in Swift.
  # https://github.com/Moya/Moya
  pod 'Moya', '~> 15.0'

  # An elegant and simple progress HUD for iOS and tvOS.
  # https://github.com/JonasGessner/JGProgressHUD
  pod 'JGProgressHUD', '2.2'

  target 'MarvelHeroesAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelHeroesAppUITests' do
    # Pods for testing
  end

end
