# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarvelHeroesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelHeroesApp
  pod 'PureLayout'

  target 'MarvelHeroesAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelHeroesAppUITests' do
    # Pods for testing
  end

end
